// بيانات كتالوج مخزني — مولّدة آلياً من الكودات المنهجية والصور.
window.PRODUCTS = [
  {
    "name": "بخاخ 100 مل شفاف",
    "sku": "BKH-100ML-TR",
    "cat": "spray",
    "catName": "بخاخات",
    "type": "بخاخ",
    "size": "100 مل",
    "color": "شفاف",
    "cap": "",
    "img": "assets/products/image1.png"
  },
  {
    "name": "بخاخ 100 مل أبيض",
    "sku": "BKH-100ML-WH",
    "cat": "spray",
    "catName": "بخاخات",
    "type": "بخاخ",
    "size": "100 مل",
    "color": "أبيض",
    "cap": "",
    "img": "assets/products/image2.png"
  },
  {
    "name": "بخاخ 100 مل أسود",
    "sku": "BKH-100ML-BL",
    "cat": "spray",
    "catName": "بخاخات",
    "type": "بخاخ",
    "size": "100 مل",
    "color": "أسود",
    "cap": "",
    "img": "assets/products/image3.png"
  },
  {
    "name": "بطل صغير 10 مل",
    "sku": "BSC-010ML-TR",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل صغير",
    "size": "10 مل",
    "color": "شفاف",
    "cap": "",
    "img": "assets/products/image4.jpeg"
  },
  {
    "name": "بطل صغير 20 مل",
    "sku": "BSC-020ML-TR",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل صغير",
    "size": "20 مل",
    "color": "شفاف",
    "cap": "",
    "img": "assets/products/image4.jpeg"
  },
  {
    "name": "بطل بني دبدوب 500 مل مع بم أسود",
    "sku": "BFT-500ML-BR-PA",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل دبدوب",
    "size": "500 مل",
    "color": "بني",
    "cap": "بم أسود",
    "img": "assets/products/image5.png"
  },
  {
    "name": "بطل بني دبدوب 300 مل مع بم أسود",
    "sku": "BFT-300ML-BR-PA",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل دبدوب",
    "size": "300 مل",
    "color": "بني",
    "cap": "بم أسود",
    "img": "assets/products/image5.png"
  },
  {
    "name": "بطل أسود سلم رفيع 300 مل مع قبغ ذهبي قلاب",
    "sku": "BSL-300ML-BL-CG",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل سليم",
    "size": "300 مل",
    "color": "أسود",
    "cap": "قبغ ذهبي قلاب",
    "img": "assets/products/image6.png"
  },
  {
    "name": "بطل أسود سلم رفيع 500 مل مع قبغ ذهبي قلاب",
    "sku": "BSL-500ML-BL-CG",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل سليم",
    "size": "500 مل",
    "color": "أسود",
    "cap": "قبغ ذهبي قلاب",
    "img": "assets/products/image6.png"
  },
  {
    "name": "بطل أبيض 300 مربع مع بم أبيض",
    "sku": "BSQ-300ML-WH-PW",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل مربع",
    "size": "300 مل",
    "color": "أبيض",
    "cap": "بم أبيض",
    "img": "assets/products/image7.png"
  },
  {
    "name": "بطل أبيض 500 مربع مع بم أبيض",
    "sku": "BSQ-500ML-WH-PW",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل مربع",
    "size": "500 مل",
    "color": "أبيض",
    "cap": "بم أبيض",
    "img": "assets/products/image7.png"
  },
  {
    "name": "كب 30 مل أبيض",
    "sku": "KB-030ML-WH",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "30 مل",
    "color": "أبيض",
    "cap": "",
    "img": "assets/products/image8.png"
  },
  {
    "name": "كب 30 مل وردي",
    "sku": "KB-030ML-PN",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "30 مل",
    "color": "وردي",
    "cap": "",
    "img": "assets/products/image9.png"
  },
  {
    "name": "كب 30 مل بني",
    "sku": "KB-030ML-BR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "30 مل",
    "color": "بني",
    "cap": "",
    "img": "assets/products/image10.png"
  },
  {
    "name": "كب 30 مل برتقالي",
    "sku": "KB-030ML-OR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "30 مل",
    "color": "برتقالي",
    "cap": "",
    "img": "assets/products/image11.png"
  },
  {
    "name": "كب 50 مل أبيض",
    "sku": "KB-050ML-WH",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "50 مل",
    "color": "أبيض",
    "cap": "",
    "img": "assets/products/image8.png"
  },
  {
    "name": "كب 50 مل وردي",
    "sku": "KB-050ML-PN",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "50 مل",
    "color": "وردي",
    "cap": "",
    "img": "assets/products/image9.png"
  },
  {
    "name": "كب 50 مل بني",
    "sku": "KB-050ML-BR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "50 مل",
    "color": "بني",
    "cap": "",
    "img": "assets/products/image10.png"
  },
  {
    "name": "كب 50 مل برتقالي",
    "sku": "KB-050ML-OR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "50 مل",
    "color": "برتقالي",
    "cap": "",
    "img": "assets/products/image11.png"
  },
  {
    "name": "كب 100 مل أبيض",
    "sku": "KB-100ML-WH",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "100 مل",
    "color": "أبيض",
    "cap": "",
    "img": "assets/products/image8.png"
  },
  {
    "name": "كب 100 مل وردي",
    "sku": "KB-100ML-PN",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "100 مل",
    "color": "وردي",
    "cap": "",
    "img": "assets/products/image9.png"
  },
  {
    "name": "كب 100 مل بني",
    "sku": "KB-100ML-BR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "100 مل",
    "color": "بني",
    "cap": "",
    "img": "assets/products/image10.png"
  },
  {
    "name": "كب 100 مل برتقالي",
    "sku": "KB-100ML-OR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "100 مل",
    "color": "برتقالي",
    "cap": "",
    "img": "assets/products/image11.png"
  },
  {
    "name": "كب 200 مل أبيض",
    "sku": "KB-200ML-WH",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "200 مل",
    "color": "أبيض",
    "cap": "",
    "img": "assets/products/image8.png"
  },
  {
    "name": "كب 200 مل وردي",
    "sku": "KB-200ML-PN",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "200 مل",
    "color": "وردي",
    "cap": "",
    "img": "assets/products/image9.png"
  },
  {
    "name": "كب 200 مل بني",
    "sku": "KB-200ML-BR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "200 مل",
    "color": "بني",
    "cap": "",
    "img": "assets/products/image10.png"
  },
  {
    "name": "كب 200 مل برتقالي",
    "sku": "KB-200ML-OR",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب",
    "size": "200 مل",
    "color": "برتقالي",
    "cap": "",
    "img": "assets/products/image11.png"
  },
  {
    "name": "كب زجاجي مضبب 20غم خيزران",
    "sku": "KBZ-020GM-CB",
    "cat": "glass",
    "catName": "زجاجيات",
    "type": "كب زجاجي",
    "size": "20 غم",
    "color": "",
    "cap": "",
    "img": "assets/products/image12.png"
  },
  {
    "name": "كب زجاجي مضبب 50غم خيزران",
    "sku": "KBZ-050GM-CB",
    "cat": "glass",
    "catName": "زجاجيات",
    "type": "كب زجاجي",
    "size": "50 غم",
    "color": "",
    "cap": "",
    "img": "assets/products/image12.png"
  },
  {
    "name": "كب زجاجي مضبب 100غم خيزران",
    "sku": "KBZ-100GM-CB",
    "cat": "glass",
    "catName": "زجاجيات",
    "type": "كب زجاجي",
    "size": "100 غم",
    "color": "",
    "cap": "",
    "img": "assets/products/image12.png"
  },
  {
    "name": "كب مرن شفاف 100 مل سلفر",
    "sku": "KBM-100ML-TR-CS",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب مرن",
    "size": "100 مل",
    "color": "شفاف",
    "cap": "غطاء سلفر",
    "img": "assets/products/image13.png"
  },
  {
    "name": "كب مرن شفاف 150 مل سلفر",
    "sku": "KBM-150ML-TR-CS",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب مرن",
    "size": "150 مل",
    "color": "شفاف",
    "cap": "غطاء سلفر",
    "img": "assets/products/image14.png"
  },
  {
    "name": "كب مرن شفاف 200 مل سلفر",
    "sku": "KBM-200ML-TR-CS",
    "cat": "cup",
    "catName": "كبّات وعلب",
    "type": "كب مرن",
    "size": "200 مل",
    "color": "شفاف",
    "cap": "غطاء سلفر",
    "img": "assets/products/image15.png"
  },
  {
    "name": "بطل بني 500 مل بم ذهبي",
    "sku": "BTL-500ML-BR-PG",
    "cat": "bottle",
    "catName": "بطلات وقناني",
    "type": "بطل",
    "size": "500 مل",
    "color": "بني",
    "cap": "بم ذهبي",
    "img": "assets/products/image16.png"
  }
];
